apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  storageClassName: "expense-ebs" # Use the default storage class
  accessModes:
    - ReadWriteOnce     
  resources:
    requests:
      storage: 4Gi 