apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector:
    app: expense
    environment: dev
    tier: mysql
    ports:
    - protocol: TCP
      port: 3306  #service port
      targetPort: 3306 #target port of the pod/container

---
apiVersion: v1
kind: Service   
metadata:
  name: mysql
  namespace: expense  
spec:
  selector: 
    app: expense
    environment: dev
    tier: mysql 
    
  ports:
    - protocol: TCP 
      port: 3306  #service port
      targetPort: 3306 #target port of the pod/container

---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql
#   namespace: expense
#   labels:
#     app: expense
#     environment: dev
#     tier: mysql
# spec:
#   storageClassName: "expense-ebs" # Use the default storage class
#   accessModes:
#     - ReadWriteOnce     
#   resources:
#     requests:
#       storage: 4Gi 
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  serviceName: "mysql-headless"
  selector:
    matchLabels:
      app: expense
      environment: dev
      tier: mysql # has to match .spec.template.metadata.labels
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: expense
        environment: dev
        tier: mysql # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      nodeSelector:
          topology.kubernetes.io/zone: us-east-1d
  volumeClaimTemplates:
    - metadata:
      name: mysql
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "expense-ebs"
        resources:
          requests:
            storage: 1Gi


